export default {
  CHANGE_SCREEN: "CHANGE_SCREEN",
  INSTALL_MUTATION: "INSTALL_MUTATION",
  INSTALL_MUTATION_REPLY: "INSTALL_MUTATION_REPLY",
  GET_PREFERENCES: "GET_PREFERENCES",
  RETURN_GET_PREFERENCES: "RETURN_GET_PREFERENCES"
};
